# Generated by Django 4.0 on 2023-04-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpcode',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='otpcode',
            name='email',
            field=models.EmailField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
