# Generated by Django 4.0 on 2023-04-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_otpcode_phone_number_otpcode_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
